# Generated by Django 5.2.7 on 2026-03-07 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESCOOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occ_uri', models.CharField(max_length=300, unique=True)),
                ('occ_label', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CareerExplorerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience_level', models.IntegerField(default=1)),
                ('cv_text_stored', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ESCOSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_uri', models.CharField(max_length=300, unique=True)),
                ('skill_label', models.CharField(max_length=300)),
            ],
            options={
                'indexes': [models.Index(fields=['skill_label'], name='career_expl_skill_l_4ca3a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('seniority_level', models.IntegerField(choices=[(0, 'Intern / Placement'), (1, 'Graduate / Junior'), (2, 'Mid'), (3, 'Senior'), (4, 'Lead')], default=1)),
                ('role_family', models.CharField(blank=True, max_length=100)),
                ('esco_occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career_explorer.escooccupation')),
            ],
        ),
        migrations.CreateModel(
            name='CareerExplorerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.FloatField()),
                ('top_missing', models.JSONField(default=list)),
                ('contrib', models.JSONField(default=dict)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='career_explorer.careerexplorerrun')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_explorer.job')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='OccupationSkillRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('essential', 'Essential'), ('optional', 'Optional')], default='essential', max_length=20)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_relations', to='career_explorer.escooccupation')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_relations', to='career_explorer.escoskill')),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['seniority_level'], name='career_expl_seniori_3fbc85_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['role_family'], name='career_expl_role_fa_3b8d01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='occupationskillrelation',
            unique_together={('occupation', 'skill')},
        ),
    ]
