# Generated by Django 6.0.2 on 2026-04-02 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('source', models.IntegerField(choices=[(0, 'Career Explorer'), (1, 'CV Matcher')], default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_prog_status', models.IntegerField(choices=[(0, 'Not started'), (1, 'In Progress'), (2, 'Done')], default=0)),
                ('skill_next_action', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.skillplan')),
            ],
        ),
        migrations.AddIndex(
            model_name='skillplan',
            index=models.Index(fields=['user'], name='tracker_ski_user_id_0da5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='skillplan',
            index=models.Index(fields=['plan_name'], name='tracker_ski_plan_na_ee9633_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedskill',
            index=models.Index(fields=['skill_name'], name='tracker_tra_skill_n_c94a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedskill',
            index=models.Index(fields=['plan'], name='tracker_tra_plan_id_f7ed18_idx'),
        ),
    ]
